# -*- coding: utf-8 -*-
"""Chat bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMomFaSIvVth-Qbpxvp_pGBAgH3WzkCv
"""

import re

import re

def chatbot():

    print("Bot: Hello! I am a simple chatbot. Type 'bye' to exit.")

    while True:

        user = input("You: ").lower()

        # Greeting intent
        if re.search(r"hello|hi|hey", user):
            print("Bot: Hi there! How can I help you?")

        # Python topic
        elif re.search(r"python", user):
            print("Bot: Python is a popular programming language used in AI, web development and data science.")

        # AI topic
        elif re.search(r"ai|artificial intelligence|machine learning", user):
            print("Bot: AI allows machines to learn from data and make decisions.")

        # Study topic
        elif re.search(r"study|exam|college", user):
            print("Bot: Try making a daily study plan and practice coding regularly.")

        # Exit
        elif re.search(r"bye|exit|quit", user):
            print("Bot: Goodbye! Have a nice day.")
            break

        # Fallback response
        else:
            print("Bot: Sorry, I didn't understand that. Can you rephrase?")

chatbot()







